name: Unit Tests

on:
  push:
    branches: [main, master]
    paths:
      - 'Source/**'
      - 'Tests/**'
      - 'ArchTests/**'
  pull_request:
    branches: [main, master]
    paths:
      - 'Source/**'
      - 'Tests/**'
      - 'ArchTests/**'

jobs:
  test:
    uses: RimWorld-RimMind-Mod/Workflows/.github/workflows/test.yml@v1
    secrets: inherit
